options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  region:
    default: RegionOne
    description: Name of the OpenStack region
    type: string
  nameservers:
    type: string
    default:
    description: |
      Space delimited list of nameservers. These are the nameservers that have
      been provided to the domain registrar in order to delegate the domain to
      Designate. e.g. "ns1.example.com. ns2.example.com."
