options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  dns-domain:
    default: cloud.sunbeam.
    description: |
      Specifies the dns domain name that should be used for building instance
      hostnames. The value of 'openstacklocal' will cause
      the dhcp agents to broadcast the default domain of openstacklocal and
      will not enable internal cloud dns resolution. This value should end
      with a '.', e.g. 'cloud.example.org.'.
    type: string
  region:
    default: RegionOne
    description: Name of the OpenStack region
    type: string
  vlan-ranges:
    default: "physnet1:1:4094"
    description: |
      Space-delimited list of <physical_network>:<vlan_min>:<vlan_max> or
      <physical_network> specifying physical_network names usable for VLAN
      provider and tenant networks, as well as ranges of VLAN tags on each
      available for allocation to tenant networks.
    type: string
  enable-igmp-snooping:
    default: False
    description: Enable IGMP snooping for integration bridge.
    type: boolean
  global-physnet-mtu:
    type: int
    default: 1500
    description: |
      MTU of the underlying physical network. Neutron uses this value to
      calculate MTU for all virtual network components. For flat and
      VLAN networks, neutron uses this value without modification. For
      overlay networks such as Geneve, neutron automatically subtracts
      the overlay protocol overhead from this value.
  path-mtu:
    type: int
    default: 1500
    description: |
      Maximum size of an IP packet (MTU) that can traverse the
      underlying physical network infrastructure without fragmentation
      when using an overlay/tunnel protocol. This option allows
      specifying a physical network MTU value that differs from the
      default global-physnet-mtu value.
  physical-network-mtus:
     type: string
     default:
     description: |
      Space-delimited list of <physical_network>:<mtu> pairs specifying MTU for
      individual physical networks.
      .
      Use this if a subset of your flat or VLAN provider networks have a MTU
      that differ with what is set in global-physnet-mtu.
  reverse-dns-lookup:
    default: False
    description: |
      A boolean value specifying whether to enable or not the creation of
      reverse lookup (PTR) records.
      .
      NOTE: Use only when integrating neutron-k8s charm to designate charm.
    type: boolean
  ipv4-ptr-zone-prefix-size:
    default: 24
    description: |
      The size in bits of the prefix for the IPv4 reverse lookup (PTR) zones.
      Valid size has to be multiple of 8, with maximum value of 24 and minimum
      value of 8.
      .
      NOTE: Use only when "reverse-dns-lookup" option is set to "True".
    type: int
  ipv6-ptr-zone-prefix-size:
    default: 64
    description: |
      The size in bits of the prefix for the IPv6 reverse lookup (PTR) zones.
      Valid size has to be multiple of 4, with maximum value of 124 and minimum
      value of 4.
      .
      NOTE: Use only when "reverse-dns-lookup" option is set to "True".
    type: int
