options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  dns-domain:
    default: cloud.sunbeam.local.
    description: |
      Specifies the dns domain name that should be used for building instance
      hostnames. The value of 'openstacklocal' will cause
      the dhcp agents to broadcast the default domain of openstacklocal and
      will not enable internal cloud dns resolution. This value should end
      with a '.', e.g. 'cloud.example.org.'.
    type: string
  os-admin-hostname:
    default:
    description: |
      The hostname or address of the admin endpoints that should be advertised
      in the neutron image provider.
    type: string
  os-internal-hostname:
    default:
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the neutron image provider.
    type: string
  os-public-hostname:
    default:
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the neutron image provider.
    type: string
  region:
    default: RegionOne
    description: Space delimited list of OpenStack regions
    type: string
  vlan-ranges:
    default: "physnet1:1:4094"
    description: |
      Space-delimited list of <physical_network>:<vlan_min>:<vlan_max> or
      <physical_network> specifying physical_network names usable for VLAN
      provider and tenant networks, as well as ranges of VLAN tags on each
      available for allocation to tenant networks.
    type: string
