- hosts: all
  roles:
    - ensure-tox
    - configure-ephemeral
    - role: use-docker-mirror
      when: env_type == 'k8s'
    - role: manual-cloud
      when: env_type == 'k8s'
    - role: lxd-cloud
      when: env_type == 'lxd'
    - zaza-func-test
